### ISSUE TITLE
AWS Lambda: become Alpakka 1.0 ready

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#1065]
- [x] Move internal code to `impl` package (#1134)
- [x] Mark internal code `@InternalApi` and `private[connector]` (#1134)
- [x] Move documentation example code to packages `docs.javadsl` and `docs.scaladsl` (#1134)
- [x] Make settings to be non-case classes (there was none)
