### ISSUE TITLE
Geode: become Alpakka 1.0 ready

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#1073]
- [x] Move internal code to `impl` package (#1096)
- [x] Mark internal code `@InternalApi` and `private[connector]` (#1096)
- [x] Move documentation example code to packages `docs.javadsl` and `docs.scaladsl` (#1096)
- [x] Make settings to be non-case classes (#1096)

**Comment by cheleb** [comment]
Should I fix all those point in a single commit ?

**Comment by ennru** [comment]
Split it in several PR if you like to do it in small steps, but one PR is OK, as well.

**Comment by 2m** [comment]
While reviewing #1096 I noticed a couple of other changes that should be done, to make Geode connector more inline with the others:

* [ ] change `ReactiveGeode` to be a collection of factory methods instead of a class that needs to be instantiated. That will mean that cache and close methods will have to move to stages themselves.
* [ ] convert Scala types to corresponding Java ones in javadsl factory methods. For example [here](https://github.com/akka/alpakka/blob/master/geode/src/main/java/akka/stream/alpakka/geode/javadsl/ReactiveGeode.java#L44).

**Comment by cheleb** [comment]
Sorry for the late reply. But AFAIK having more then one (active) cache per jvm is not that easy (https://geode.apache.org/releases/latest/javadoc/org/apache/geode/cache/client/ClientCacheFactory.html#create--) 
I will try to investigate further.

**Comment by cheleb** [comment]
Is there a chance that akka extension mechanism should fit to hold the Geode cache (aka connection) ?
