### ISSUE TITLE
Build for Scala 2.13 milestone

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#828]
Depends on:
* [x] https://github.com/sullis/jms-testkit/issues/4
* [ ] akka/akka-grpc#506 (google-cloud-pub-sub-grpc, depending on https://github.com/scalapb/ScalaPB/issues/540)
* [ ] https://github.com/slick/slick/issues/1958
* [x] https://github.com/pauldijou/jwt-scala/issues/115 (google-fcm, google-cloud-pub-sub)
* [ ] https://github.com/hseeberger/akka-http-json/issues/253 (ironmq)
* [ ] https://jira.mongodb.org/browse/SCALA-506 (mongodb)
* [ ] matsluni/aws-spi-akka-http/issues/3 (sns, sqs)

**Comment by ennru** [comment]
akka-stream will soon become available for Scala 2.13-M4.

**Comment by 2m** [comment]
The `aws-spi-akka-http` dependency `s3mock` depends on Alpakka S3 in the test scope. It has come full circle. We will have to start publishing 2.13-M5 artifacts for the Alpakka connectors that are not blocked by any dependencies so others can catch up.

**Comment by matsluni** [comment]
@2m, I am the author of `aws-spi-akka-http`. Would it makes sense to drop `s3mock` for something which is not dependent on alpakka? I guess that would simplify things?!

@gabssilva suggested @localstack.
Do you know any other alternatives?

**Comment by 2m** [comment]
Most of the Alpakka connectors (S3 included) have a few Scala dependencies and are not blocked for support of Scala 2.13. So we will be releasing artifacts for those that are built with Scala 2.13 quite soon. This will unblock `s3mock`. However if you see a viable alternative, like localstack, then it might make things easier in the future, when subsequent Scala 2.13 releases are out.
